import type { Metadata } from "next";
import { Geist, Geist_Mono, Alata, Jost, Orienta, IBM_Plex_Serif, Roboto, Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";
import ScheduledPostChecker from "@/components/ScheduledPostChecker";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const alata = Alata({
  weight: '400',
  variable: "--font-alata",
  subsets: ["latin"],
});

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});

const orienta = Orienta({
  weight: "400",
  variable: "--font-orienta",
  subsets: ["latin"],
});

const ibm_plex_serif = IBM_Plex_Serif({
  weight: ["700", "500"],
  variable: "--font-ibm_plex_serif",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Birat Info",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <script type="text/javascript" src={`https://platform-api.sharethis.com/js/sharethis.js#property=${process.env.NEXT_PUBLIC_SHARETHIS_URL}&product=inline-share-buttons&source=platform`} async></script>
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${alata.variable} ${jost.variable} ${orienta.variable} ${ibm_plex_serif.variable} ${roboto.variable} ${inter.variable} antialiased`}
        >
          <>
            <ClerkLoading>
              <div className="flex items-center justify-center min-h-screen">
                <div className="animate-spin rounded-full h-16 w-16 border-t-4 border-green-500 border-solid" />
              </div>
            </ClerkLoading>

            <ClerkLoaded>
              <ScheduledPostChecker />
              {children}
              <Toaster position="top-right" toastOptions={{ duration: 3000 }} />
            </ClerkLoaded>
          </>
        </body>
      </html>
    </ClerkProvider>
  );
}
